menu:
- {name: 'about', url: '/about'}
- {name: 'research', url: '/research'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

about:
- {name: 'Publications', url: 'publications'}
- {name: 'Portfolio', url: 'portfolio'}

social:
- {icon: 'github', link: 'https://github.com/ancantu'}
- {icon: 'twitter', link: 'https://twitter.com/_ancan2'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/ancantu33'}

contact:
- {name: 'Alyssa Cantu', title: 'PhD student', department: 'Computer Science', institution: 'Rice University', institution_address: '6100 Main Street, Houston, TX', email: 'anc5@rice.edu', office: 'DH 3037', image: 'assets/img/anc.jpg'}
